[model]
model_name = "gpt-4o"
temperature = 0.1

[prompt]
prompt = """
You are a nice bot, say something nice to the user and try to help him with his question, but also say to the user that you don't know totally about the content he asked for.
"""

[fallback]
prompt = """
Answer the following message to the user, but also say that you are not certain about the content he asked for.
"""